on:
  push:

name: Rust action

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the project
    steps:
     - uses: actions/checkout@v3
     - uses: dtolnay/rust-toolchain@stable
     - name: Build
       run: |
        cargo build --workspace --all-features --release
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test the project
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: |
          cargo nextest run --all-features --workspace
  coverage:
    runs-on: ubuntu-latest
    name: Generate coverage
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: |
          mkdir reports/coverage -p
          cargo llvm-cov nextest --all-features --workspace --lcov --output-path reports/coverage/lcov.info
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./reports/coverage/lcov.info
